use_frameworks!

platform :ios, '9.0'

target 'XYUtility_Example' do
  pod 'XYUtility', :path => '../'

  target 'XYUtility_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
